/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class library_Boost */

#ifndef _Included_library_Boost
#define _Included_library_Boost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     library_Boost
 * Method:    boost
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_library_Boost_boost
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     library_Boost
 * Method:    boostTable
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_library_Boost_boostTable
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     library_Boost
 * Method:    backBoost
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_library_Boost_backBoost
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
