/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_model_update_jni_MessageJNI */

#ifndef _Included_app_model_update_jni_MessageJNI
#define _Included_app_model_update_jni_MessageJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_model_update_jni_MessageJNI
 * Method:    messageSend
 * Signature: (Lcn/sgepri/adapter/bus/Message;I)I
 */
JNIEXPORT jint JNICALL Java_app_model_update_jni_MessageJNI_messageSend
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     app_model_update_jni_MessageJNI
 * Method:    messageInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_model_update_jni_MessageJNI_messageInit
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     app_model_update_jni_MessageJNI
 * Method:    messageReceive
 * Signature: (Lcn/sgepri/adapter/bus/Message;)I
 */
JNIEXPORT jint JNICALL Java_app_model_update_jni_MessageJNI_messageReceive
  (JNIEnv *, jclass, jobject);

/*
 * Class:     app_model_update_jni_MessageJNI
 * Method:    messageSubscribe
 * Signature: (SLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_model_update_jni_MessageJNI_messageSubscribe
  (JNIEnv *, jclass, jshort, jstring);

/*
 * Class:     app_model_update_jni_MessageJNI
 * Method:    messageUnSubscribe
 * Signature: (SLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_model_update_jni_MessageJNI_messageUnSubscribe
  (JNIEnv *, jclass, jshort, jstring);

/*
 * Class:     app_model_update_jni_MessageJNI
 * Method:    messageExit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_model_update_jni_MessageJNI_messageExit
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
